department-for-transport-BODS/publish-devolved-bus-registration-data

.github/workflows/build.yml, .github/workflows/deploy.yml
Updating jobs to reflect environmental variables
=> Update GHA for environments

frontend/src/pages/home.tsx, frontend/src/pages/privacyStatement.tsx
=> Change title

.github/workflows/build.yml, .github/workflows/deploy.yml, sql/g.epReport.sql
Updated build and deploy jobs to package SQL files as database migrations, and uploaded for versioning with backend + frontend components. Deployment invokes a lambda function with the required parameters which sees the relevant version's files downloaded and executed in order against the database.
If `latest` is provided as the version number, S3 is interrogated to provide the latest available (non-dev) release candidate version, which is subsequently deployed.
=> [BODS-4377] DB Migration Mechanism

backend/src/csv_handler/utils/db.py, frontend/src/pages/home.tsx, frontend/src/pages/privacyStatement.tsx
This branch fixes the following bug tickets:
- https://kpmgengineering.atlassian.net/browse/BODS-4448
- https://kpmgengineering.atlassian.net/browse/BODS-4318
=> Fixing bugs

backend/src/csv_handler/managers/csv_manager.py, backend/src/csv_handler/utils/db.py, sql/g.pdbrdRegistration.sql
This branch adds `routeNumber` to the Registered record unique identifier.
=> [BODS-3805] Add route number to unique record check

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/modify-db.yml
Added job to allow for modification of the database using GHA. This includes initialisation, destruction, and updates using the latest release version.
Updated deployment job to allow for isolated deployments of either database, or application components.
=> [BODS-2751] Extended DB Functionality

backend/template.yml
Updated template.yml with code necessary to associate alias + certificate with CF distribution
=> [BODS-4441] Production Ready Infra

backend/src/csv_handler/utils/db.py
This branch adds the ability to search for multiple `service code` at once from the UI  utilising `licence_number/service_code1/service_code2/...`
=> [BODS-4307] BSOG multi search UI

frontend/src/pages/accessibilityStatement.tsx, frontend/src/pages/contactUs.tsx, frontend/src/pages/privacyStatement.tsx
- https://kpmgengineering.atlassian.net/browse/BODS-4712
- https://kpmgengineering.atlassian.net/browse/BODS-4713
- https://kpmgengineering.atlassian.net/browse/BODS-4715
=> BODS fix bugs

backend/template.yml
Added S3Av Policy for access to S3 from CSV Handler Lambda
=> [BODS-2686] MIssing Permissions on ClamAV

backend/src/csv_handler/app.py, backend/src/csv_handler/auth/verifier.py, backend/src/csv_handler/managers/csv_manager.py, backend/src/csv_handler/utils/aws.py, backend/src/csv_handler/utils/db.py, backend/src/csv_handler/utils/exceptions.py, backend/src/csv_handler/utils/pydant_model.py, backend/src/weca_client/utils/db.py, backend/template.yml, frontend/src/pages/home.tsx, frontend/src/pages/preValidation.tsx, frontend/src/pages/uploadCsv.tsx, frontend/src/utils/SendCsv.tsx, sql/f.pdbrdStage.sql
This branch address ClamAv timeout when uploading csv file.
=> Fix ClamAv time out issue 

backend/template.yml
Uncommented changes to assign ACM Certificate with CF Distribution
=> [BODS-5651] Production Ready

backend/src/otc_client/app.py, backend/src/weca_client/utils/weca_api.py, backend/template.yml
Updated template to reference shared SSM parameters
Migrated environment specific secrets to shared
=> [BODS-6433]

backend/template.yml
Associating created WAF with CloudFront distribution to assist in mitigation of attacks.
=> [BODS-6449] WAF 

backend/src/data_catalogue/app.py, backend/src/weca_client/utils/db.py
Missing modules in some files.
=> [BUGFIX] Missing Modules

frontend/src/Layout/Footer.tsx, frontend/src/pages/basic.tsx, frontend/src/pages/default.tsx
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> [BODS-3630] Footer

frontend/src/Layout/Footer.tsx, frontend/src/pages/basic.tsx, frontend/src/pages/default.tsx
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> [BODS-3630]

VERSION, backend/src/csv_handler/utils/constants.py, backend/src/csv_handler/utils/pydant_model.py, backend/tests/csv_handler/test_app.py
Adding a validation for the `application type` field.
=> [BODS 6526] service type validation

VERSION, frontend/src/components/TableRow.tsx, frontend/src/pages/login.tsx, frontend/src/pages/registrationDetails.tsx, frontend/src/utils/ChangeDateFormat.tsx
This ticket is about change date format from `yyyy-mm-dd` to `dd-mm-yyyy`.
=> [BODS-6842] Fix date format in search page

VERSION, frontend/src/components/SearchResults.tsx, frontend/src/pages/registrationDetails.tsx
Update search result to show `route number` as `service number`
=> update route number to show service number

backend/src/csv_handler/utils/db.py
Added new filter value for active registrations, to include 'Variation' in addition to 'New' / 'Change'
=> Updated to capture 'Variation' in active registrations

VERSION, backend/src/csv_handler/utils/db.py, backend/src/csv_handler/utils/validate.py
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> [BODS-7153] Open up read-only content

VERSION, backend/src/otc_client/app.py, frontend/src/utils/Search.tsx
=> Bug fix/remove dotenv
